
services:
  trac:
    image: trac520
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYPROJECT_ADMIN: lanka
        MYPROJECT_ADMIN_PASS: 123456
        MYPROJECT_TRACDIR: /var/trac
        MYPROJECT_NAME: lanka520
    container_name: hello-trac
    volumes:
      - ../auth:/var/trac/auth
      - ../conf/trac.ini:/var/trac/conf/trac.ini
      - ../repositories:/var/trac/repositories
      - ../sites-available/trac.wsgi:/var/trac/www/trac.wsgi
      - ../sites-available/trac.conf:/etc/apache2/sites-available/trac.conf
      - ../sites-available/svn.conf:/etc/apache2/sites-available/svn.conf
      - ../sites-available/git.conf:/etc/apache2/sites-available/git.conf
    ports:
      - "9981:80"
